function _ = write_text_file(data, title_)
    file = fopen(strcat("./autogenerated_data/", title_, ".txt"), 'w');
    fprintf(file, '%1s %1s %1s %1s %1s %1s %1s %1s %1s\r\n', "t", "Wilson", "Newmark1", "Newmark2", "Newmark3",
    "Central Difference", "Constant Approximation", "Linear Approximation", "Analytical");
    fprintf(file, '%1f %1f %1f %1f %1f %1f %1f %1f %1f\r\n', data);
    fclose(file);
end
